DEBUG: true

# ESPECIFICACIONES DE LA MEMORIA
RAM_SIZE: 64 # in KB

# ESPECIFICACIONES DE LA CPU

# ESPECIFICACIONES DE LA PANTALLA
SCREEN_WIDTH: 400
SCREEN_HEIGHT: 400

# RUTA DE ARCHIVOS
URL_STATISTICS: ''